/*
  Author: garadha@microsoft.com
  Dated: 09-23-2018
  Description:
  This pipeline defines the stages and steps for building and deploying the 'po-service' application
  to AKS.
*/
node {
	def app

	stage('Clone repository') {
		sh 'echo "Cloning GitHub repository ..."'
		checkout scm
	}

	docker.image('maven:3-alpine').inside('-v $HOME/.m2:/root/.m2') {
		stage('Appl. Build') {
			sh 'echo "Building application ..."'
			sh 'mvn -DskipTests clean package'
		}
	}

	stage('Print Data ... ') {
		sh 'echo "Present working directory ..."'
		sh 'pwd'
	}

	stage('Container Build & Tag') {
		sh 'echo "Building application container image ..."'
		app = docker.build("${ACR_LOGINSERVER}/po-service:${env.BUILD_TIMESTAMP}.${env.BUILD_ID}", ". -f ./src/Dockerfile")
	}

	stage('Push Container Image To ACR') {
		sh 'echo "Pushing container image to ACR ..."'
		docker.withRegistry('https://${ACR_LOGINSERVER}','acr-credentials') {
			app.push()
			app.push("latest")
		}
	}

	stage('Deploy to AKS') {
		sh 'echo "Using Helm to upgrade application (redeploy) on AKS"'
	}
}
